[package]
name = "ot-portfolio"
version.workspace = true
edition.workspace = true

[dependencies]
ot-types = { workspace = true }
ot-common = { workspace = true }
ot-config = { workspace = true }
ot-risk = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
statrs = { workspace = true }
