[package]
name = "ot-common"
version.workspace = true
edition.workspace = true

[dependencies]
ot-types = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
