[package]
name = "ot-live"
version.workspace = true
edition.workspace = true

[dependencies]
ot-types = { workspace = true }
ot-common = { workspace = true }
ot-config = { workspace = true }
ot-market-data = { workspace = true }
ot-features = { workspace = true }
ot-strategy = { workspace = true }
ot-risk = { workspace = true }
ot-portfolio = { workspace = true }
ot-execution = { workspace = true }
ot-exchange-binance = { workspace = true }
ot-storage = { workspace = true }
ot-telemetry = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
